FROM python:3.10-slim-buster

WORKDIR /pakistani_news_LLM_app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY scraper.py scraper.py

ENV PYTHONPATH /pakistani_news_LLM_app
CMD [ "python3", "scraper.py"]